theme: minima
title: Chiara Molinari
description: PhD Student in Mathematics

minima:
  social_links:
    - name: linkedin
      username: chiara-molinari-4ab532255
    - name: github
      username: ChiaraM00